export const FETCH_SERVICE_REQUEST = "FETCH_SERVICE_REQUEST";

export const FETCH_SERVICE_RECEIVED = "FETCH_SERVICE_RECEIVED";

export const FETCH_SERVICE_FAILED = "FETCH_SERVICE_FAILED";

export const SUBMIT_QUOTE_REQUEST = "FETCH_QUOTE_REQUEST";

export const SUBMIT_QUOTE_RECIEVED = "FETCH_QUOTE_RECIEVED";

export const SUBMIT_QUOTE_FAILED = "FETCH_QUOTE_FAILED";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";

export const ADD_USER_RECEIVED = "ADD_USER_RECEIVED";

export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";

export const LOGIN_USER_RECEIVED = "LOGIN_USER_RECEIVED";

export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";

export const LOGOUT_USER_RECEIVED = "LOGOUT_USER_RECEIVED";

export const BOOK_SERVICE_REQUEST = "BOOK_SERVICE_REQUEST";

export const BOOK_SERVICE_FAILED = "BOOK_SERVICE_FAILED";

export const BOOK_SERVICE_RECEIVED = "BOOK_SERVICE_RECEIVED";

export const FETCH_BOOKING_REQUEST = "FETCH_BOOKING_REQUEST";

export const FETCH_BOOKING_FAILED = "FETCH_BOOKING_FAILED";

export const FETCH_BOOKING_RECEIVED = "FETCH_BOOKING_RECEIVED";

export const CANCEL_BOOKING_REQUEST = "CANCEL_BOOKING_REQUEST";

export const CANCEL_BOOKING_FAILED = "CANCEL_BOOKING_FAILED";

export const CANCEL_BOOKING_RECEIVED = "CANCEL_BOOKING_RECEIVED";